#!/usr/bin/env ruby
# Habiter: simple habit tracking
# add or update habit:
#   'habiter did clean_room'
# view habit graph:
#   'habiter graph'

require 'yaml'
require 'optparse'

# Stolen from ActiveSupport
class Time
  def to_date
    ::Date.new(year, month, day)
  end unless method_defined?(:to_date)
end
  

@habiter_file = File.expand_path('~/.habiter.yaml')

begin
  @habits = YAML::load_file(@habiter_file)
rescue
  File.open(@habiter_file, 'w').close()
end

@habits = {} unless @habits

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: habiter.rb [options]"
end


def did(key)
  if not @habits.has_key?(key)
    print "#{key} is not a habit yet. create and complete it? (y/n) "
    if STDIN.gets.chomp == 'y'
      @habits[key] = [Time.now]
    end
  else
    @habits[key] << Time.now
  end
  File.open(@habiter_file, 'w') do |f|
    YAML.dump(@habits, f)
  end
end


def graph(options={})
  options[:days] = 30 unless options[:days]
  day = Date.today - options[:days] * 86400
  @habits.each do |habit, times|
    print sprintf("%10s | ", habit)
    times.collect! do |time|
      time.to_date
    end
    (0..options[:days]).each do |i|
      if times.include? day
        print "+"
      else
        print "-"
      end
      day += 86400
    end
    puts
  end
end

if ARGV[0] == 'did'
  did(ARGV[1])
elsif ARGV[0] == 'graph'
  graph()
end
